FROM gradle:8.5-jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
# Accept build arguments
ARG SPRING_PROFILES_ACTIVE
ARG DATABASE_HOST
ARG DATABASE_SCHEMA
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG NOTIFICATION_SERVICE_URL

# Set these arguments as environment variables
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_SCHEMA=${DATABASE_SCHEMA}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}

RUN gradle build -x test --no-daemon

FROM openjdk:21-slim AS production
EXPOSE 8080
RUN mkdir /app
# Accept build arguments
ARG SPRING_PROFILES_ACTIVE
ARG DATABASE_HOST
ARG DATABASE_SCHEMA
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG NOTIFICATION_SERVICE_URL

# Set these arguments as environment variables
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_SCHEMA=${DATABASE_SCHEMA}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}

COPY --from=build /home/gradle/src/build/libs/*.jar /app/subscription-service.jar
ENTRYPOINT ["java","-jar","app/subscription-service.jar"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]